version: 2

sources:
  - name: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales table
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        freshness:
           warn_after:
            count: 90
            period: day
      - name: product
        identifier: raw_gz_product
        description: product table
        columns:
          - name: products_id
            description: products ID
            tests:
             - unique
             - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ship table
        columns:
          - name: orders_id
            description: orders ID
            tests:
             - unique
             - not_null

models:
   - name: int_orders_margin
     description: margin per orders and per days
     columns:
       - name: orders_id
         description: orders ID
         tests:
           - unique
           - not_null
       - name: revenue
         description: revenue per orders
         tests:
           - not_null
       - name: quantity
         description: quantity
         tests:
           - not_null                 
          
   - name: int_orders_operational
     description: operation margin per orders and per days
     columns:
       - name: orders_id
         description: orders ID
         tests:
           - unique
           - not_null
              
              