version: 2
sources:
  - name: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales table
      - name: product
        identifier: raw_gz_product
        description: product table
      - name: ship
        identifier: raw_gz_ship
        description: ship table